### ISSUE TITLE
Bots can not set vanity URLs

### ISSUE THREAD

**Issue by Permanently** [umutxyp/Discord-Vanity-URL-Sniper#1]
When inspecting the URL request sent from the bot, this response is received:

`{ message: 'Bots cannot use this endpoint', code: 20001 }`

**Comment by umutxyp** [comment]
I made an edit on ready.js but I did not test it, please check if the problem persists.

**Comment by umutxyp** [comment]
> When inspecting the URL request sent from the bot, this response is received:
> 
> `{ message: 'Bots cannot use this endpoint', code: 20001 }`

I made an edit on ready.js but I did not test it, please check if the problem persists.

**Comment by umutxyp** [comment]
fixed
