### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by MathiX1108** [umutxyp/Discord-Vanity-URL-Sniper#5]
It would be necessary to ensure that it can snipe a level 3 loss URL: explanation, a URL is on the server, level 3 of the server is lost, so no longer a high enough level to keep the URL, except that it cannot be taken for 1 month and it does not snipe the URL.

Similarly, having the possibility to snipe a BAN URL, in case it is unbanned.

**Comment by umutxyp** [comment]
> It would be necessary to ensure that it can snipe a level 3 loss URL: explanation, a URL is on the server, level 3 of the server is lost, so no longer a high enough level to keep the URL, except that it cannot be taken for 1 month and it does not snipe the URL.
> 
> Similarly, having the possibility to snipe a BAN URL, in case it is unbanned.

I am not god or the owner of the discord. If there is such a thing, the discord can solve it, not these codes.
